# Specific modification of Easy Template for Reaper Digital Audio Workstation, to open multiple projects at once.

import os
import shutil
import calendar
import sys

def generate_template_folders(month, year, day, num_parents, num_subfolders, use_template, subfolder_prefix, output_path=None):
    # If output_path is not provided, use the current working directory
    output_path = output_path or os.getcwd()

    # Calculate the day of the week for the 1st day of the month
    first_day_of_month = calendar.weekday(year, month, 1)

    # Find the first occurrence of the specified day in the month
    first_occurrence = (day - first_day_of_month + 7) % 7 + 1

    # Generate parent folders for the specified day of the week
    for i in range(num_parents):
        current_day = first_occurrence + (i * 7)

        # Adjust for rollover into the next month
        while current_day > calendar.monthrange(year, month)[1]:
            current_day -= calendar.monthrange(year, month)[1]
            month += 1
            if month > 12:
                month = 1
                year += 1

        # Create root folder for the month, year, and specified day
        root_folder = os.path.join(output_path, f"ET {year}-{month:02d}-{current_day:02d} {calendar.day_name[day]}")
        os.makedirs(root_folder)

        # Generate subfolders
        for j in range(1, num_subfolders + 1):
            subfolder_name = f"{subfolder_prefix}{j:02d}" if subfolder_prefix else f"Session_{j:02d}"
            subfolder = os.path.join(root_folder, subfolder_name)
            os.makedirs(subfolder)

            # Create .rpp files with content from the template files
            template_folder = "Template"

            # Handle subfolder template files
            subfolder_template_folder = os.path.join(template_folder, "sub")
            for template_file in os.listdir(subfolder_template_folder):
                template_path = os.path.join(subfolder_template_folder, template_file)

                if use_template and os.path.isfile(template_path):
                    target_file_name = f"project{j:02d}.rpp"  # Adjusted naming for project files
                    target_path = os.path.join(subfolder, target_file_name)
                    shutil.copy(template_path, target_path)
                    print(f"Subfolder template file created: {target_path}")

        # Create README.md file in the parent folder
        readme_path = os.path.join(root_folder, "README.md")
        with open(readme_path, "w") as readme_file:
            readme_file.write("# Root README.md\n\nGenerated by etgen.py")

        # Create OpenAllProjects.RPL file in the parent folder with shortened project paths
        open_all_projects_path = os.path.join(root_folder, "OpenAllProjects.RPL")
        with open(open_all_projects_path, "w") as open_all_projects_file:
            for j in range(1, num_subfolders + 1):
                project_number = str(j).zfill(2)  # Increment project_number for each session
                project_path = os.path.join(f"Session_{j:02d}", f"project{project_number}.rpp")
                open_all_projects_file.write(f"{project_path}\n")

        print(f"README.md file created at: {readme_path}")
        print(f"OpenAllProjects.RPL file created at: {open_all_projects_path}")

if __name__ == "__main__":
    # Get user input
    month = int(input("Enter the month (1-12): "))
    year = int(input("Enter the year: "))

    # Display numbered list of days
    days_of_week = list(calendar.day_name)
    for i, day in enumerate(days_of_week, start=1):
        print(f"{i}. {day}")

    day_number = int(input("Enter the number corresponding to the day of the week: "))
    selected_day = days_of_week[day_number - 1]

    num_parents = int(input("Enter the number of parent folders (1 or more): "))
    num_subfolders = int(input("Enter the number of subfolders (1-100, or more with caution): "))

    # Warn if more than 100 subfolders
    if num_subfolders > 100:
        user_response = input(
            "⚠️ Warning: Specifying more than 100 subfolders may impact system performance. Do you want to proceed? (yes/no): ").lower()

        if user_response != "yes":
            print("Operation canceled. Please run the script again with a lower number of subfolders.")
            sys.exit()

    use_template = input("Do you want to use template files? (yes/no): ").lower() == "yes"
    subfolder_prefix = input("Enter a prefix for subfolders (press Enter for default 'Session'): ")

    # Ask if the user wants to specify a custom output path
    custom_output_path = input("Do you want to specify a custom output path? (press Enter to use default path): ")
    
    # If the user provides a custom output path, use it; otherwise, set it to None
    output_path = custom_output_path if custom_output_path else None

    # Generate template folders
    generate_template_folders(month, year, days_of_week.index(selected_day), num_parents, num_subfolders, use_template,
                              subfolder_prefix, output_path)

    print("Template folders created successfully!")
